[firebase]
type = "service_account"
project_id = "stock-ai-dashboard"
private_key_id = "8be709e0acd0c31df78c0513bb9702dcaedca279"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJCbEmy5RSDvnf
VzFRJmQBYj0sDLz/HLMPmJyquvVWDj0TG27DrA/9o5mqbiPBOkm1kEcdFAIweBED
...
ZUE2IkksTeqhREaIHdiJGdk=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@stock-ai-dashboard.iam.gserviceaccount.com"
client_id = "106967726007227537448"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@stock-ai-dashboard.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
